name: mobile_mechanic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  introduction_screen: ^3.1.14
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

